"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2exe
"""

from distutils.core import setup
import py2exe

APP = ['db_test.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False}

setup(
    console=APP
)
